# Generated by Django 2.0.2 on 2023-12-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231214_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_post',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
