# Generated by Django 2.0.2 on 2023-12-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20231214_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_des',
            new_name='description',
        ),
    ]
